# Generated by Django 4.0.4 on 2022-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='unit',
            new_name='measurement_unit',
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('habit', 'tracked_date'), name='daily_record_limit'),
        ),
    ]
