# Generated by Django 4.0.4 on 2022-05-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_habit_goal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(help_text='Please enter date as MM/DD/YYYY'),
        ),
    ]
